### ISSUE TITLE
Couldn't make a connection

### ISSUE THREAD

**Issue by matanos** [RedisJSON/JRedisJSON#22]
Hi ,

I've started a redis-redisjson container and loaded the module as seen below: 
![image](https://user-images.githubusercontent.com/16700272/81671050-31622980-9451-11ea-88b2-cebde4929779.png)

now when trying to reach out the server from my java client - using 1.2.0 version I 
keep get this message inside the JreJSON client:
java.lang.Exception
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:147)
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:110)
	at redis.clients.jedis.util.Pool.initPool(Pool.java:45)
	at redis.clients.jedis.util.Pool.<init>(Pool.java:24)
	at redis.clients.jedis.JedisPoolAbstract.<init>(JedisPoolAbstract.java:15)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:221)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:165)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:137)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:76)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:120)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:103)
	at redis.clients.jedis.JedisPool.<init>(JedisPool.java:26)
	at com.redislabs.modules.rejson.JReJSON.<init>(JReJSON.java:99)
	at io.redis.jedis.jedisdemo.JedisDemoApplication.start(JedisDemoApplication.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.redis.jedis.jedisdemo.JedisDemoApplication.main(JedisDemoApplication.java:47) . 

The code is trivial as in your examples and my container is listening to port 6379  
``	JReJSON client = new JReJSON();
		JReJSON client1 = new JReJSON("localhost", 6379);
		JReJSON client2 = new JReJSON("127.0.0.1", 6379);` `
all these clients are failing . 
May you please advise? 

Thanks

**Comment by gkorland** [comment]
@matanos did you manage to create a connection?

**Comment by bsbodden** [comment]
@matanos can you connect to your container using the local redis-cli? or telnet? I suspect it's a docker networking issue.
